version: '3.8'

services: 
  nocodb: 
    depends_on: 
      - nocodb_root_db
      - nocodb_redis
    environment: 
      NC_DB: "pg://nocodb_root_db:5432?u=postgres&p=password&d=nocodb-db"
      NC_AUTH_JWT_SECRET: ${NC_AUTH_JWT_SECRET}
      NC_PUBLIC_URL: ${NC_PUBLIC_URL}
      NC_REDIS_URL: "redis://nocodb_redis:6379/1" 
    image: "nocodb/nocodb:latest"
    networks:
      - nocodb-nw
    ports: 
      - "58080:8080"
    restart: unless-stopped
    volumes: 
      - /opt/apps/persistence/nocodb/data:/usr/app/data
  
  nocodb_root_db:
    networks:
      - nocodb-nw
    environment: 
      POSTGRES_DB: nocodb-db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/db
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      timeout: 2s
    image: postgres:15-alpine
    restart: unless-stopped
    volumes: 
      - /opt/databases/prod/nocodb/postgresql/db:/var/lib/postgresql/db

  nocodb_redis:
    networks:
      - nocodb-nw
    image: redis:7-bookworm
    restart: unless-stopped

networks:
  nocodb-nw:
    driver: bridge
