version: '3.8'

services: 
  nocodb: 
    depends_on: 
      # - nocodb_root_db
      - nocodb_redis
    environment: 
      NC_AUTH_JWT_SECRET: ${NC_AUTH_JWT_SECRET}
      NC_PUBLIC_URL: ${NC_PUBLIC_URL}
      NC_REDIS_URL: "redis://nocodb_redis:6379/1" 
    image: "nocodb/nocodb:0.255.2"
    networks:
      - nocodb-nw
    ports: 
      - "58080:8080"
    restart: unless-stopped
    env_file:
      - .env
    volumes: 
      - /mnt/glusterfs/db.jsmx.org/app/data:/usr/app/data
    deploy:
      replicas: 2  # Run two replicas
      restart_policy:
        condition: any
  
  # nocodb_root_db:
  #   networks:
  #     - nocodb-nw
  #   environment: 
  #     POSTGRES_DB: nocodb-db
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: postgres
  #     PGDATA: /var/lib/postgresql/db
  #   healthcheck: 
  #     interval: 10s
  #     retries: 10
  #     test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
  #     timeout: 2s
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   volumes: 
  #     - /mnt/glusterfs/db.jsmx.org/postgresql/db:/var/lib/postgresql/db
  #   deploy:
  #     restart_policy:
  #       condition: any

  nocodb_redis:
    networks:
      - nocodb-nw
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      replicas: 2  # Run two replicas for Redis
      restart_policy:
        condition: any

networks:
  nocodb-nw:
    driver: overlay
